### ISSUE TITLE
Annotation resource CSV export uses old/missing resource API and causes a 500

### ISSUE THREAD

**Issue by an-fischer** [VedaWebProject/Tekst#410]
There is an error „background task generate resource export failed“ when trying to export data from resource type „annotation“ as .csv. Info: The .json export works for all resource types. The .csv export works for resource type „text“.

**Comment by an-fischer** [comment]
#408

**Comment by bkis** [comment]
Oh boy, thanks. This happens because [here](https://github.com/VedaWebProject/Tekst/blob/b851910a6a8bec5f33fb14e018a536ac674ba32c/Tekst-API/tekst/resources/text_annotation.py#L260) the API code tries to access the resource's aggregated annotation data in the wrong way. The way those aggregations are managed and stored changed recently – I guess I forgot to update the code for the CSV export accordingly.

Thanks!
